---
title: "Midterm"
author: "Rithin Gujja"
date: "29/10/2019"
output: html_document
---
## 1Q) ##
```{r}
mid<-read.csv("Universities.csv")
test<-mid
mid1<-mid[complete.cases(mid),]
colMeans(is.na(mid1))*100
```
## 2Q) ##
```{r}
library(factoextra)
library(tidyverse)
library(ISLR)
library(caret)
set.seed(100)
md<-mid1[,c(-1,-2,-3)]
md1<-scale(md)

k3<-kmeans(md1,centers = 3,nstart = 30)
k3
k3$centers
k3$size
fviz_cluster(k3,data = md1)
fviz_nbclust(md1,kmeans,method = "wss")
fviz_nbclust(md1,kmeans,method = "silhouette")
k3$cluster[3]
k3$withinss
```
## 3Q) ##
```{r}
viz<-cbind(mid1,k3$cluster)
summary(viz[viz$`k3$cluster`=="1",])
summary(viz[viz$`k3$cluster`==2,])
summary(viz[viz$`k3$cluster`==3,])
## by seeing the cluster centers and confirming by taking the summary of the individual customers we get  
## Rejected rate is more in cluster  1 with max of 48094 and low in cluster     3 with 77
## accepted rate is more in cluster  1 with max of 2737 and low in cluster      2 with value 61
## new enrolled is more in cluster   1 with max of 1567 and low in cluster      2 with value 27  
## students top10 is more in cluster 3 with max of 96 and low in cluster        2 with value 1 
## students top20 is more in cluster 3 with max of 100 and low in cluster       2 with value 9
## f.t undergrad is more in cluster  1 with max of 31643 and low in cluster     2 with value 249
## PT Undergrad is more in cluster   1 with max of 21836 and low in cluster     3 with value 1
## in state fee is more in cluster   3 with max of 20100 and low in cluster     2 with value 15476
## out state fee is more in cluster  3 with max 20100 and low in cluster        2 with value 1044
## Room rent is more in cluster      3 with max of 4816 and low in cluster      2 with a value of 640
## Board cost is more in cluster     3 with max of 4541 and low in cluster      2 with value of 531
## Extra fees is more in cluster     1 with max value 3247 and low in cluster   2 with value of 10
## book cost is more in cluster      2 with max value 2340 and low in cluster   2 with value of 90
## personal cost is more in cluster  3 with value of 6800 and low in cluster    2 with value of 250
## fac to phd is more in cluster     1 with max value  70 and low in cluster    2 with value of 8
## stu :fac ratio is more in cluster 2 with max value 28.80 and low in cluster  3 with value of 2.9 
## grad rate is more in cluster      2 with max value of 118 and low in cluster 2 with a value of 15
```
## 4Q) ##
```{r}
head(viz[,c(1,2,3,21)])
## there is no relation between the categorical data and the clusters
```
## 5Q) ##
```{r}
## By seeing the summary statistics of the individual clusters, Cluster 1 has the best schools with stud to faculty ratio, number of rejections,acceptance and enrolled students and the fee structure.
## Sum of squares is also low in cluster 1 when compared to 2 and 3.
```

## 6Q) ##
```{r}
filter(mid,College.Name=="Tufts University")
test$X..PT.undergrad[is.na(test$X..PT.undergrad)]=mean(test$X..PT.undergrad,na.rm = TRUE)
filter(test,College.Name=="Tufts University")

set.seed(100)
test2<-na.omit(test)
t1<-test2[,c(-1,-2,-3)]
t2<-scale(t1)
k4<-kmeans(t2,centers = 3,nstart = 30)
k4$cluster
which(grepl("Tufts University",mid$College.Name))
l6<-cbind(test2,k4$cluster)
filter(l6,College.Name=="Tufts University")%>%select(21)
## Tufts university is in the cluster 2 based on the euclidean distance.
```
