---
title: "ml2 assignment"
author: "Rithin Gujja"
date: "24/10/2019"
output: html_document
---
## data Partition ##
```{r}
getwd()
ml2<-read.csv("UniversalBank.csv")
library(dplyr)
library(caret)
library(ISLR)
ml1<-select(ml2,Age,Experience,Income,Family,CCAvg,Education,Mortgage,Personal.Loan,Securities.Account,CD.Account,Online,CreditCard)
set.seed(15)
Train_Index=createDataPartition(ml1$Age,p=0.6,list=FALSE)
Train_Data=ml1[Train_Index,]
Validation_Data=ml1[-Train_Index,]
```
## normalization ##
```{r}
Train.nf<-Train_Data
Validation.nf<-Validation_Data
norm.values<-preProcess(Train_Data[,-8],method=c("center","scale"))
Train.nf[,-8]<-predict(norm.values,Train_Data[,-8])
Validation.nf[,-8]<-predict(norm.values,Validation_Data[,-8])
summary(Train.nf)
```
## creating factors ##
```{r}
Train_Data$Personal.Loan<-factor(Train_Data$Personal.Loan,levels = c(0,1),labels = c("deny","accept"))
Validation_Data$Personal.Loan<-factor(Validation_Data$Personal.Loan,levels = c(0,1),labels = c("deny","accept"))
```
## KNN modelling
```{r}
library(FNN)
nn<-knn(train=Train.nf[,-8],test=Validation.nf[,-8],cl=Train_Data$Personal.Loan,k=1,prob=TRUE)
head(nn)
levels(nn)
```
## Cross Table ##
```{r}
library(gmodels)
CrossTable(x=Validation_Data$Personal.Loan,y=nn,prop.chisq = FALSE)
```
## finding the best k ##
```{r}
library(caret)
Bestk <- data.frame(k = seq(1, 55, 1), accuracy = rep(0, 55))

for(i in 1:55) {
  knn.pred <- knn(Train.nf[,-8],Validation.nf[,-8],
                  cl =Train_Data$Personal.Loan, k = i)
  Bestk[i,2]<-confusionMatrix(knn.pred,Validation_Data$`Personal.Loan`)$overall[1]
}
Bestk

Bestk[which.max(Bestk$accuracy),]
```
## confusion matrix for best k=4##
```{r}
library(FNN)
nn<-knn(train=Train.nf[,-8],test=Validation.nf[,-8],cl=Train_Data$Personal.Loan,k=4,prob=TRUE)
library(gmodels)
CrossTable(x=Validation_Data$Personal.Loan,y=nn,prop.chisq = FALSE)
```
## predicting for the customer ##
```{r}
c1<-data.frame("Age"=40,"Experience"=10,"Income"=84,"Family"=2,"CCAvg"=2,"Education"=1,"Mortgage"=0,"Personal.Loan"=0,"Securities.Account"=0,"CD.Account"=0,"Online"=1,"CreditCard"=1)
c2<-data.frame("Age"=40,"Experience"=10,"Income"=84,"Family"=2,"CCAvg"=2,"Education"=2,"Mortgage"=0,"Personal.Loan"=1,"Securities.Account"=0,"CD.Account"=0,"Online"=1,"CreditCard"=1)
c3<-data.frame("Age"=40,"Experience"=10,"Income"=84,"Family"=2,"CCAvg"=2,"Education"=3,"Mortgage"=0,"Personal.Loan"=0,"Securities.Account"=0,"CD.Account"=0,"Online"=1,"CreditCard"=1)
cc<-as.data.frame(rbind(c1,c2,c3))
class(cc)

cc.norm<-cc[,-8]
nor<-preProcess(cc.norm,method=c("center","scale"))
ll.norm<-predict(nor,cc.norm)
pp<-knn(Train.nf[,-8],ll.norm,cl=Train_Data$Personal.Loan,k=4,prob = TRUE)
pp
```
## splitting into test,train and validation sets ## 
```{r}
Train_Index1 <- createDataPartition(ml1$Age,p=0.5, list=FALSE) 
Train_Data1 = ml1[Train_Index1,]
Test_Index1 <- createDataPartition(ml1$Age,p=0.2, list=FALSE)
Test_Data1 = ml1[Test_Index1,]
Validate_Index1 <- createDataPartition(ml1$Age,p=0.3, list=FALSE)
Validate_Data1 = ml1[Validate_Index1,]

summary(Train_Data1)
summary(Test_Data1)
summary(Validate_Data1)

## normalization

Train.nf1<-Train_Data1
Validate.nf1<-Validate_Data1
Test.nf1<-Test_Data1

norm.values2<-preProcess(Train_Data1[,-8],method=c("center","scale"))
Train.nf1[,-8]<-predict(norm.values2,Train_Data1[,-8])
Test.nf1[,-8]<-predict(norm.values2,Test_Data1[-8])
Validate.nf1[,-8]<-predict(norm.values2,Validate_Data1[,-8])

summary(Train.nf1)
summary(Validate.nf1)

##creating levels for personal loan

Train_Data1$Personal.Loan<-factor(Train_Data1$Personal.Loan,levels = c(0,1),labels = c("deny","accept"))
Validate_Data1$Personal.Loan<-factor(Validate_Data1$Personal.Loan,levels = c(0,1),labels = c("deny","accept"))
Test_Data1$Personal.Loan<-factor(Test_Data1$Personal.Loan,levels = c(0,1),labels = c("deny","accept"))

```
## KNN Modelling training set ##
```{r}
library(FNN)
nnn1<-knn(train=Train.nf1[,-8],test=Train.nf1[,-8],cl=Train_Data1$Personal.Loan,k=4,prob=TRUE)
head(nnn1)
library(gmodels)
CrossTable(x=Train_Data1$Personal.Loan,y=nnn1,prop.chisq = FALSE)
## we got the accuracy of 97.72% in the training data set ##
```
## KNN Modelling test set ##
```{r}
library(FNN)
nnn2<-knn(train=Train.nf1[,-8],test=Test.nf1[,-8],cl=Train_Data1$Personal.Loan,k=4,prob=TRUE)
head(nnn2)
library(gmodels)
CrossTable(x=Test_Data1$Personal.Loan,y=nnn2,prop.chisq = FALSE)
## we got an accuracy of 97.40% in the test data set ##
```
## KNN Modelling in validation set ##
```{r}
library(FNN)
nnn3<-knn(train=Train.nf1[,-8],test=Validate.nf1[,-8],cl=Train_Data1$Personal.Loan,k=4,prob=TRUE)
head(nnn3)
library(gmodels)
CrossTable(x=Validate_Data1$Personal.Loan,y=nnn3,prop.chisq = FALSE)
## We got an accuracy of 97.66% ##

## From the Test data set to the Train data set we differ by an accuracy of 0.32% ##
## We got the 0.32% difference because we took the data partition of the test data as 20% and Train data as 50% so the test data has more data to analyse and give the more accuracy than the Test data set.
   

## From the Test data set to the Validation data set we differ by accuracy of 0.26% ##
## We got the 0.26% difference because we took the validation data as 30% and test data as 20% the validation partition has more data to predict and give more accuracy rate then the Test data set.

```
